name: log_smoothing
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=hd63d673_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - asttokens==3.0.1
      - astunparse==1.6.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - chex==0.1.91
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - etils==1.13.0
      - executing==2.2.1
      - flatbuffers==25.12.19
      - flax==0.12.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - humanize==4.15.0
      - idna==3.11
      - importlib-resources==6.5.2
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jax==0.8.2
      - jax-cuda12-pjrt==0.8.2
      - jax-cuda12-plugin==0.8.2
      - jaxlib==0.8.2
      - jedi==0.19.2
      - joblib==1.5.3
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - keras==3.13.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - msgpack==1.1.2
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - numpy==2.4.0
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.17.1.4
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.5.19
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optree==0.18.0
      - orbax-checkpoint==0.11.31
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.2
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - simplejson==3.20.2
      - six==1.17.0
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorstore==0.1.80
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - treescope==0.1.10
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - zipp==3.23.0
